### ISSUE TITLE
lesson-blocks appearing huge with empty space on firefox

### ISSUE THREAD

**Issue by bosuh** [NUKnightLab/learncms#12]
![screen shot 2015-08-17 at 4 25 34 pm](https://cloud.githubusercontent.com/assets/12286846/9316740/8e1e2484-44fc-11e5-836a-c5b9402eb29e.png)

**Comment by thehandsomepanther** [comment]
I don't see it, do you know when it happens?

![screen shot 2015-08-21 at 9 23 57 am](https://cloud.githubusercontent.com/assets/6078575/9410522/60aef946-47e6-11e5-8756-8af4c6494059.png)

**Comment by JoeGermuska** [comment]
This doesn't seem to be a universal issue. Closing. If it is something that turns out to be consistently reproducible, please open a new issue with a clear instruction on how to see the problem.
