### ISSUE TITLE
zooming-image trigger not visible on light images

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/learncms#20]
people can't really see the magnifying glass on things like

![image](https://cloud.githubusercontent.com/assets/46313/9555611/cc81853c-4d93-11e5-8ebc-c610aa61c002.png)

**Comment by zachwise** [comment]
closed by https://github.com/NUKnightLab/learncms/commit/3b3ad3bd16df6f3029f4d49e2d1e43e88d2a7fb6
