### ISSUE TITLE
Back + Forward browser buttons not working

### ISSUE THREAD

**Issue by AditiBhandari** [NUKnightLab/learncms#23]
I'm using Chrome on a Mac, and I've found that when I use the back button in the browser to go to the previous module, the URL changes but the page doesn't, and I have to refresh the page in order to get there instead (same thing with the forward button). I've also found that when a card in a lesson links out to another lesson, the sidebar where the lesson is supposed to appear is just a grey block, and I need to refresh the page for it to appear.
![screen shot 2015-08-28 at 4 13 22 pm](https://cloud.githubusercontent.com/assets/9308945/9557202/c28ca74e-4d9f-11e5-853b-8d7a7190b6ba.png)

**Comment by JoeGermuska** [comment]
Looks like it was a mistake to merge in updates to the polymer web components. For now I've reverted this, so the basic functionality works. It was not necessary to do the merge, even though it seemed like a good idea to keep up with changes to the polymer code. I have that stuff off in a branch for more testing before we try it.

Now, it seems that clicking on the stacked pages to go back has the too-many-backs problem, but that's not this bug, so closing this one.
