### ISSUE TITLE
Hyperlinks lost their formatting

### ISSUE THREAD

**Issue by AditiBhandari** [NUKnightLab/learncms#30]
They just look like regular text instead of being blue and underlined

**Comment by JoeGermuska** [comment]
Now that is really annoying. By all of my understanding of the encapsulation that web components have, that shouldn't have had any impact outside the `learn-nav` component. Anyway, I made a more specific CSS selector which solves the issue.

**Comment by JoeGermuska** [comment]
Aha! We've been using `::content` all wrong! But now I get it. I think.
