### ISSUE TITLE
Header attribute on lesson-block doesn't seem to do anything

### ISSUE THREAD

**Issue by emilywithrow** [NUKnightLab/learncms#41]
Unlike step-block, I'm not seeing the result of the "header" text as an h2. I've been implementing manually, even though the attribute is there.

**Comment by JoeGermuska** [comment]
just an oversight!

**Comment by emilywithrow** [comment]
This doesn't seem to be working.

**Comment by JoeGermuska** [comment]
really, it's fixed.

![image](https://cloud.githubusercontent.com/assets/46313/9917525/bba686f6-5c87-11e5-8c4c-e54716f1eedd.png)
