### ISSUE TITLE
Capsule unit gets cut off when opened in a sublesson

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/learncms#5]
![screen shot 2015-08-10 at 8 47 20 am](https://cloud.githubusercontent.com/assets/6078575/9173005/da8615e0-3f3c-11e5-824b-05afd0360f56.png)

**Comment by JoeGermuska** [comment]
This is trickier than I thought, so reopening and marking for other review, but I think I have it.

**Comment by JoeGermuska** [comment]
this seems done.
