### ISSUE TITLE
Ctrl + F seems to only read part of the edit window

### ISSUE THREAD

**Issue by emilywithrow** [NUKnightLab/learncms#50]
Since the CMS doesn't "remember" where you were editing, I rely on it to find my place.... halp

**Comment by JoeGermuska** [comment]
see also https://github.com/codemirror/CodeMirror/issues/221

**Comment by JoeGermuska** [comment]
Say more about what you want remembered. We might be able to do something about it.

**Comment by emilywithrow** [comment]
Typically when I see an error on the page, I'll jump in to edit, but it's
tedious to have to sort through all the markup to find the text I'm looking
for. It would be awesome if I could place my cursor in the text editor and
then ctrl + F the keyword I'm looking for, to jump to that spot to edit.
Would be a huge time saver.

**Comment by JoeGermuska** [comment]
Looks like this could help, even if it's a little awkward

https://codemirror.net/demo/search.html

**Comment by JoeGermuska** [comment]
Closed. Note that you have to be in the content field for cmd-F to activate search within the content. Otherwise, hopefully it satisfies. There may be some adjustments we could make to the behavior if you like.

**Comment by emilywithrow** [comment]
YAY YAY YAY thanks
