### ISSUE TITLE
Style ol ul li 

### ISSUE THREAD

**Issue by emilywithrow** [NUKnightLab/learncms#82]
See https://learn.knightlab.com/lesson/intro-web-hosting/ for example

![screen shot 2015-10-15 at 10 51 20 am](https://cloud.githubusercontent.com/assets/798614/10519335/d2b4aefe-732a-11e5-9cc2-76a5ed73a804.png)

**Comment by zachwise** [comment]
I think this was just broken html. I went in and fixed it. 
![google chrome](https://cloud.githubusercontent.com/assets/741789/10523895/74ac4d9a-7342-11e5-9654-eda02549ea82.png)

**Comment by emilywithrow** [comment]
Oh... thanks! Don't know why I didn't think to check that. :/
