### ISSUE TITLE
Placing ul inside ol breaks style for subsequent list items

### ISSUE THREAD

**Issue by emilywithrow** [NUKnightLab/learncms#83]
See https://learn.knightlab.com/lesson/intro-web-hosting/ for example

![screen shot 2015-10-15 at 10 55 19 am](https://cloud.githubusercontent.com/assets/798614/10519425/4ea11822-732b-11e5-8d9f-67eafe0fe0c4.png)

**Comment by zachwise** [comment]
This is just broken html. The second item for the `ol` is not in the `ol` and also the `ul` should be inside a `li`.
