### ISSUE TITLE
text overflow wrap for code block breaks when window is resized for certain blocks (needs overflow-wrap: break-word?)

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/learncms#9]
text overflow works correctly at max window width:
![screen shot 2015-08-12 at 11 23 46 am](https://cloud.githubusercontent.com/assets/6078575/9229859/db721702-40e4-11e5-8201-5625083a2537.png)

text overflow breaks for the src attribute in code example here:
![screen shot 2015-08-12 at 11 23 50 am](https://cloud.githubusercontent.com/assets/6078575/9229860/db7b9a84-40e4-11e5-9b8e-5df44bc66c58.png)

works fine here however:
![screen shot 2015-08-12 at 11 25 18 am](https://cloud.githubusercontent.com/assets/6078575/9229861/db7bdd8c-40e4-11e5-9c77-dd8638c4df33.png)

**Comment by bosuh** [comment]
this happens with reference blurbs too, except when you make the window very large

![screen shot 2015-08-17 at 3 30 38 pm](https://cloud.githubusercontent.com/assets/12286846/9315446/dd77c268-44f4-11e5-9d40-bff22390655d.png)

**Comment by thehandsomepanther** [comment]
fixed by 88aebcf29368a381b08acb610fbc0ad084d87c70
